version: 2.0.{build}
skip_commits:
  message: /NO-BUILD/
  files:
    - docs/*
    - 'LICENSE'
    - 'README.md'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
before_build:
  - ps: nuget restore
image: Visual Studio 2017
configuration: Release
build:
  parallel: true 
  verbosity: minimal
test:
  assemblies:
    only:
      - '**\bin\**\*.UnitTests.dll'
test_script:
  - cmd: "\"%USERPROFILE%\\.nuget\\packages\\OpenCover\\4.6.519\\tools\\OpenCover.Console.exe\" -register:user -target:\"%xunit20%\\xunit.console.x86.exe\" -targetargs:\"Grumpy.ServiceBase.UnitTests\\bin\\Release\\Grumpy.ServiceBase.UnitTests.dll -noshadow\" -output:\"coverage.xml\" -filter:\"+[Grumpy.ServiceBase*]* -[Grumpy.ServiceBase.UnitTests*]*\""
after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" -t 8e35b3f4-8408-4c47-949a-25daaa352ea9
after_build:
  - ps: nuget pack Grumpy.ServiceBase\bin\Release\Grumpy.ServiceBase.nuspec -Version $env:APPVEYOR_BUILD_VERSION
artifacts:
  - path: '**\*.nupkg'
    name: NuGet
deploy:
  provider: Environment
  name: NuGet
